// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByNa0GrXu3pfb3TD6M0gbAu5uCDV7eyac',
    appId: '1:384650436532:web:2af765bcff3fb1ce7a5ce1',
    messagingSenderId: '384650436532',
    projectId: 'redit-clone-3ce82',
    authDomain: 'redit-clone-3ce82.firebaseapp.com',
    storageBucket: 'redit-clone-3ce82.appspot.com',
    measurementId: 'G-EJLE8DG2JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgi99deXO5fT1_Lq7VphSQIFYWRhO0rQQ',
    appId: '1:384650436532:android:14bc820746998fa47a5ce1',
    messagingSenderId: '384650436532',
    projectId: 'redit-clone-3ce82',
    storageBucket: 'redit-clone-3ce82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACcNSqxqIm38rdH8fR5495EARhJij9vyw',
    appId: '1:384650436532:ios:ea000e1d3b1391e87a5ce1',
    messagingSenderId: '384650436532',
    projectId: 'redit-clone-3ce82',
    storageBucket: 'redit-clone-3ce82.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACcNSqxqIm38rdH8fR5495EARhJij9vyw',
    appId: '1:384650436532:ios:ea000e1d3b1391e87a5ce1',
    messagingSenderId: '384650436532',
    projectId: 'redit-clone-3ce82',
    storageBucket: 'redit-clone-3ce82.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByNa0GrXu3pfb3TD6M0gbAu5uCDV7eyac',
    appId: '1:384650436532:web:e39f9deb75c5f17c7a5ce1',
    messagingSenderId: '384650436532',
    projectId: 'redit-clone-3ce82',
    authDomain: 'redit-clone-3ce82.firebaseapp.com',
    storageBucket: 'redit-clone-3ce82.appspot.com',
    measurementId: 'G-ZQQBBXZ78Q',
  );
}
